### ISSUE TITLE
Bar chart count sometimes differs from count of filtered records displayed in table view

### ISSUE THREAD

**Issue by johnmhoran** [nexB/scancode-workbench#285]
This behavior sometimes comes up, for example, with selecting the `Copyright Statements` option in the bar chart: we might see a count of 5 for `No Value Detected`, but after clicking on that bar, only 3 records are displayed in the table view.

The behavior seems related to a combination of:
* The manner in which `Copyright Statements`, `Copyright Holders` and `Copyright Authors` are related to one another in the count calculation.  (Not sure if it applies to license information as well.)
* The fact that a count of 5 in the bar chart does not necessarily refer to 5 separate records -- might be 4 occurrences in 1 record and 1 occurrence in a second record.

The first bullet is probably something we'd want to address; the second bullet seems more an issue of design and explaining to users what the count represents.

**Comment by majurg** [comment]
It would be interesting to know if this behavior can be observed with any other "attributes" (license, package etc).

**Comment by johnmhoran** [comment]
Agreed @majurg .  My guess is for license info, yes -- the nature of the data allows multiple values per record, which seems at least partly related to the behavior.  Not sure about package info -- isn't that one value per record for the vrious attributes?  In any event, I'll keep my eyes peeled.  Should we discuss this as possibly the next issue (or set of issues) for me to tackle?

**Comment by majurg** [comment]
@johnmhoran This issue is now fixed in the latest develop and will be apart of the next release package. 

Now the bar chart will correctly reflect the number of files that contain one or more of any particular attributes (a license key for example). 

Keep in mind, the bar chart number represent the number of FILES that contain or do not contain a particular attribute. This will need to be reflected in docs somewhere, as directories are not counted in the barChart, but would show up when filtering by "No Value"

For now #343 is merged and I will close this ticket.
