### ISSUE TITLE
view "Directory Tree" does not work

### ISSUE THREAD

**Issue by krutztq** [nexB/scancode-workbench#393]
### Description
The view "Directory Tree" does not work, I only see the top directory of my scan. If I want to open/expand it, a "Processing.." pops up very short and the "expand icon" dissapears. 
Are there any known issues?
Do I have to consider anything (e.g. dir of json-file, dir of running scancode-workbench)?

### System configuration
For bug reports, it really helps us to know:
* What OS are you running on? (Windows/MacOS/Linux)
Ubuntu 18.04.2 LTS
* What version of scancode-workbench are you running on?
Scancode Workbench Version 3.1.0 (build from develop branch - commit 2cd0d32)
* What version of scancode-toolkit was used to generate the scan file?
ScanCode version: 3.1.1

**Comment by majurg** [comment]
@krutztq Sometimes very large scanfile sizes (> 100 MB+) can create problems. 

Can you upload you scanfile to a gist or other location so I can reproduce this?

**Comment by tq-krutzc** [comment]
The size is about 21 kB, here is the file:
https://gist.github.com/krutztq/a3fa93e9c8c229b1d25cc0dd7598ad1b

**Comment by steven-esser** [comment]
@krutztq I can reproduce this with your supplied file and it is certainly some sort of UI bug. I will have to dig a little into this to figure out whats going on. Thanks for the report!

**Comment by steven-esser** [comment]
@krutztq After taking a look at this bug, it looks like the culprit is the `--only-findings` option used during the initial scancode-toolkit scan. This option limits the results file to only list the files/directories that have some sort of license, copyright, email, etc detection. The net effect is `scancode-workbench` cannot recreate the full file tree properly using this limited set of information. 

However, this should be supported. I have added a new ticket here: https://github.com/nexB/scancode-workbench/issues/404

As a stopgap, you can re-run your scan without using the `--only-findings` option and the tree view should work properly.
